### ISSUE TITLE
AttributeError: module 'zhipuai' has no attribute 'model_api'

### ISSUE THREAD

**Issue by D-D3** [calvinweb/zhipuai_langchain#2]
报错了：
#>>> response = chat_model.generate("Hello, how are you?")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda3\envs\biogpt\lib\site-packages\langchain_core\language_models\chat_models.py", line 408, in generate
    raise e
  File "D:\anaconda3\envs\biogpt\lib\site-packages\langchain_core\language_models\chat_models.py", line 398, in generate
    self._generate_with_cache(
  File "D:\anaconda3\envs\biogpt\lib\site-packages\langchain_core\language_models\chat_models.py", line 577, in _generate_with_cache
    return self._generate(
  File "E:\zhipuai_langchain-main\zhipuai_langchain-main\zhipuai_langchain\__init__.py", line 92, in _generate
    response = zhipuai.model_api.invoke(
AttributeError: module 'zhipuai' has no attribute 'model_api'

是不是因为zhipuai改了呀？，您测试了吗

**Comment by lin-calvin** [comment]
现在langchain已经有了ZHIPUAI的集成了，所以说这个库不再应该被使用了，也被废弃了。

**Comment by D-D3** [comment]
不好意思我是小白，我2024-02-03通过pip install-Ulangchain_openai安装 lagnchain，这里的没有zhipuai呀？请您给我解答一下，或如何导入zhipuqi，万分感谢！
![ff9b7991098c196ea7452fa1d7ff655](https://github.com/calvinweb/zhipuai_langchain/assets/132031225/ecf053ce-91d1-45e8-83b9-c2db21443a1e)

**Comment by lin-calvin** [comment]
> 不好意思我是小白，我2024-02-03通过pip install-Ulangchain_openai安装 lagnchain，这里的没有zhipuai呀？请您给我解答一下，或如何导入zhipuqi，万分感谢！ ![ff9b7991098c196ea7452fa1d7ff655](https://private-user-images.githubusercontent.com/132031225/302021313-ecf053ce-91d1-45e8-83b9-c2db21443a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NDc0MTIsIm5iZiI6MTcwNjk0NzExMiwicGF0aCI6Ii8xMzIwMzEyMjUvMzAyMDIxMzEzLWVjZjA1M2NlLTkxZDEtNDVlOC04M2I5LWMyZGIyMTQ0M2ExZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwNzU4MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTliOWIxZjFiNDEwMDJmNjkzZDI1ZDVlODM5MTZiNGRiMmQ2ODE3YWQxNDdmOWU5NGQ5ZjRiYWRhMTQwYTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DR-QvjVluqT1oLpNWNvXbHTespVidwB9m4taH7-7wtM)

现在langchian在逐步把这些集成转移到`langchain_community`，所以说这个在`langchain_community.chat_models`里面，详细可以参考[https://python.langchain.com/docs/integrations/chat/zhipuai](https://python.langchain.com/docs/integrations/chat/zhipuai)

**Comment by D-D3** [comment]
谢谢！
